FROM node:22.20.0-alpine AS base

WORKDIR /app

FROM base AS build

ENV HUSKY=0

COPY package*.json ./
COPY apps/server/package.json ./apps/server/package.json
COPY apps/worker/package.json ./apps/worker/package.json
COPY apps/web/package.json ./apps/web/package.json
COPY packages/shared/package.json ./packages/shared/package.json
COPY .husky/install.mjs ./.husky/install.mjs
RUN npm ci

COPY . .
RUN npm run build -w @ffmpeg-rest/web

FROM base AS runtime

RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001

COPY --from=build --chown=nodejs:nodejs /app/apps/web/.output ./.output

USER nodejs

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
